name: TEST

on:
  push:
    branches: ['master', 'dev']
  pull_request:
    branches: ['master', 'dev']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - name: Install Dependencies
        run: npm install
      - name: Create .env file
        run: |
          echo "TZ=Asia/Ho_Chi_Minh" >> .env
          echo "PORT=8080" >> .env

      - run: npm run build --if-present
      - run: npm start
